### ISSUE TITLE
Multiboot Flags don't affect structure output

### ISSUE THREAD

**Issue by tuckotb** [thepowersgang/rust_os#10]
Trying to get the multiboot structure doesn't yield any changes when changing the flags in start.S, I am compiling for amd64. I get the mboot_ptr by "externing" it in the main file. I use bindgen-cli to generate multiboot.rs with the flags ``--use-core --impl-debug``. I then attempt to get the struct like this
```
unsafe {
        let struct1 = ((mboot_ptr as usize) + 0xFFFFFFFF80000000) as *mut multiboot_info;
        let struct2: &mut multiboot_info = struct1.as_mut().unwrap();
        log!("{:?}", struct2);
    }
```
I have let the assembly file unchanged from the clone and have also tried this from scratch with no success. Any attempts to fix this always prints out the same values
```
[kernel] multiboot_info { flags: 591, mem_lower: 639, mem_upper: 129920, boot_device: 2147549183, cmdline: 1101824, mods_count: 0, mods_addr: 1101824, u: multiboot_info__bindgen_ty_1 { union }, mmap_length: 168, mmap_addr: 36864, drives_length: 0, drives_addr: 0, config_table: 0, boot_loader_name: 1101846, apm_table: 0, vbe_control_info: 0, vbe_mode_info: 0, vbe_mode: 0, vbe_interface_seg: 0, vbe_interface_off: 0, vbe_interface_len: 0, framebuffer_addr: 0, framebuffer_pitch: 0, framebuffer_width: 0, framebuffer_height: 0, framebuffer_bpp: 0, framebuffer_type: 0, __bindgen_anon_1: multiboot_info__bindgen_ty_2 { union } }
```
I have also looked in to your ``rust-os`` but don't see how I could fix it, the only difference I see is that you use NASM.

Thanks for any help.

**Comment by thepowersgang** [comment]
1. I'm not sure how much this relates to this project - did you clone the `rust_os` repo and start fiddling with the early boot code?
2. You haven't provided much detail as to how you get the `mboot_ptr` value - are you sure it's valid?
3. Using `{:x?}` would be clearer, as most of those values are either pointers or bitsets.

You may have better luck asking for help on either the `#os-dev` channel on the rust community discord, or on the `libera.chat#osdev` IRC channel

**Comment by tuckotb** [comment]
I did not clone the ``rust_os`` repo, I was just looking aronud to see how you implemented it. The mboot_ptr value I get from the assembly after startup like this
```
extern "C" {
static mboot_ptr: u32;
}
```
I will also try asking around on the #osdev channel for sure, I didn't know it existed but thanks for informing me.

**Comment by tuckotb** [comment]
Oh wait I posted this in the wrong repo 🤦 I meant to post this in the ``rust-barebones-kernel`` repo. I am very sorry but I will try asking around in the Rust Discord.
