### ISSUE TITLE
Heads-up: -Csoft-float is a NOP on the targets you support (and will soon be deprecated)

### ISSUE THREAD

**Issue by RalfJung** [thepowersgang/rust_os#11]
I stumbled upon this use of `-Csoft-float`:

https://github.com/thepowersgang/rust_os/blob/dd31d840c2723327d3f9530761b1307cda00a781/Kernel/Makefile.old#L92

This flag is a NOP on all targets except for 32bit ARM `*hf` targets. Given that the docs say "the current version is x86_64/amd64", it should be the case that this flag can be removed without any change in behavior. In particular, to my knowledge the comment indicating that this avoids the use of SSE on x86 targets is incorrect. See https://github.com/rust-lang/rust/issues/129893 for more context.

**Comment by thepowersgang** [comment]
@RalfJung  Does that apply to the `soft-float` target feature? (in the JSON target spec)?

**Comment by RalfJung** [comment]
No, this is entirely about the `-C` flag.

The soft-float target feature has some issues (see https://github.com/rust-lang/rust/issues/116344), but it *does* have an effect, and our plan is to keep allowing it for the cases where it is sound and error only when it is unsound. (And it will always be usable in the JSON target spec, that is the safest place to set it.)

**Comment by thepowersgang** [comment]
That was removed in d4d558c, so cool :)
