### ISSUE TITLE
Is there a floppy image build of RustOS? (to test it inside the coreboot/SeaBIOS)

### ISSUE THREAD

**Issue by informer2016** [thepowersgang/rust_os#5]
Dear @thepowersgang , your previous creation AcessOS had a live floppy. Please tell, is there a floppy image build of RustOS, and - if not - is it theoretically possible? Open source coreboot/SeaBIOS supports booting the virtual floppy images stored inside its' ROM, and because this coreboot is much smaller than crappy proprietary UEFI _(instead of 4MB takes less than 1MB of my coreboot-supported laptop's BIOS chip)_ now I have a lot of space which could be used to store interesting OS such as your Acess or Rust ! But only the floppy media formats are supported there, although luckily not just 1.44MB but also 2.88MB...

**Comment by thepowersgang** [comment]
There is no floppy image, and while it is _theoretically_ possible, it's not going to be very useful (due to not having a flopper driver)
