### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by ids1024** [thepowersgang/rust_os#6]
This seems like a neat project. Though, the `README` does seem to lack build instructions. Building an OS is generally not simple, and I'm having some trouble doing so.

I ran `ARCH=amd64 ./BuildCrossCompiler`. It failed to compile on my (Arch Linux) system, annoyingly. But I was able to fix that by bumping the binutils and gcc versions in that script to the versions Arch currently uses.

It seemed I also needed to manually set `PATH` to include the built toolchain.

Then `make UPDATE`, and `make`. Which works.

But now, `make run` fails:

```
../../Usermode/.output/amd64/bin: No such file or directory
```

**Comment by thepowersgang** [comment]
Confirmed. Been quite while since I did a clean build. I'm working on fixing everything now (did a bad switch to using xargo for userland and didn't notice)

**Comment by ids1024** [comment]
Having some kind of CI can be helpful to catch this sort of issue. (I guess probably with a pre-built tool-chain; then it should have an acceptable run time).

**Comment by thepowersgang** [comment]
well... there is, but it doesn't check that `run` works

**Comment by ids1024** [comment]
Ah, for some reason I missed the `.travis.yml`. Yeah, making sure the CI tests `run` (somehow) would help.

**Comment by thepowersgang** [comment]
236dfdca5660372ea6d4c3f1eea463dbd2c2945d fixes the userland build issues, appears to work now (boots at least)

**Comment by ids1024** [comment]
I ran into a couple more issues, addressed in https://github.com/thepowersgang/rust_os/pull/7 and https://github.com/thepowersgang/rust_os/pull/8.

I also had to remove the `-q` argument to `mkisofs`, which doesn't seem to be a valid argument... I'm not sure what's going on there.

**Comment by thepowersgang** [comment]
Not sure what it was meant to do, might have been an alias for `-quiet` originally. I haven't used the ISO build for quite a while (generally use PXE) so it may have bit-rotted.
